# Automatically generated by configure - do not modify!
shared=no
build_suffix=
prefix=/mnt/d/WorkSpace/emsdk/wasmlearning/FFMPEGSDK/ffmpeg-3.4.8/../dist
libdir=${prefix}/lib
incdir=${prefix}/include
rpath=
source_path=.
LIBPREF=lib
LIBSUF=.a

extralibs_avutil="  -lm"
extralibs_avcodec="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avformat="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avdevice="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avfilter="-s USE_SDL=2 -s USE_SDL=2 -lm  "
extralibs_avresample="-lm"
extralibs_postproc=""
extralibs_swscale="-lm"
extralibs_swresample="-lm "
avcodec_deps="swresample avutil"
avdevice_deps="avformat avcodec swresample avutil"
avfilter_deps="swscale avformat avcodec swresample avutil"
avformat_deps="avcodec swresample avutil"
avresample_deps="avutil"
avutil_deps=""
postproc_deps="avutil"
swresample_deps="avutil"
swscale_deps="avutil"
